### ISSUE TITLE
 Cannot find name 'QueueIt'.

### ISSUE THREAD

**Issue by harshachaitanya** [queueit/cordova-sdk#1]
Ionic3 with Cordova 
When we are trying to run the app, we are 

```
import {QueueIt} from 'cordova-queue-it';
node_modules/cordova-queue-it/types/index.d.ts' is not a module.ts(2306)
```     
we are not able to run the also.

**Comment by johowoo** [comment]
You don't need to import QueueIT at all, it has been attached to the "window" Object.
Therefore, you can just run `QueueIT.run(...)` or `window.QueueIT.run(...)` without having to import it.
By the way, if you are using TypeScript, you probably need `// @ts-ignore` on the top of this line.

**Comment by sp0x** [comment]
Like @johowoo said, you don't need to import QueueIt. It's a global function.
node_modules/cordova-queue-it/types/index.d.ts was added just so that the type definition was available.
